name: Expense-tracker ci-pipeline
on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew build --no-daemon
